### ISSUE TITLE
mvn repo down

### ISSUE THREAD

**Issue by timbru31** [gravitylow/Updater#27]
Hi,

I hope this is the right place for this.
Currently your Jenkins and Maven repo seem to be down. (http://repo.gravitydevelopment.net/)
In case this is wanted, please close the issue.
Otherwise, it would be great if you can fix this issue, since builds are failing now :lollipop: 

Cheers,
Tim

**Comment by confuser** [comment]
I've setup a mirror on the Frostcast CI server in case this is affecting anyone having build problems

```
<repository>
    <id>confuser-repo</id>
    <url>http://ci.frostcast.net/plugin/repository/everything</url>
</repository>
```

**Comment by Fear837** [comment]
http://ci.frostcast.net/plugin/repository/everything
also seems to be down :(

**Comment by timbru31** [comment]
@Fear837 
I've mirrored it too:
WebApp: http://repo.dustplanet.de/artifactory/webapp/#/artifacts/browse/tree/General/ext-release-local/net/gravitydevelopment/updater/updater/2.3/updater-2.3.jar

Direct access:
http://repo.dustplanet.de/artifactory/ext-release-local

**Comment by gravitylow** [comment]
Sorry folks. I've reuploaded the artifacts, can someone please confirm it's working?

**Comment by gravitylow** [comment]
Closing this out, if there are any more issues feel free to reopen.

**Comment by val59000** [comment]
Hello,

The repository is down again. Can you restart it ? Thanks !

```
Downloading: http://repo.gravitydevelopment.net/net/gravitydevelopment/updater/updater/maven-metadata.xml
[WARNING] Could not transfer metadata net.gravitydevelopment.updater:updater/maven-metadata.xml from/to gravity-repo (http://repo.gravitydevelopment.net): Failed to transfer file: http://repo.gravitydevelopment.net/net/gravitydevelopment/updater/updater/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
```

**Comment by gravitylow** [comment]
@val59000 Sorry -- hosting company threw a fit. I'll try and have it up as soon as I can.

**Comment by val59000** [comment]
Hello @gravitylow ,
It is still offline. Can you check again please ?
Thank you

**Comment by timbru31** [comment]
@val59000 again, see my comment, I've mirrored it, too :)

> I've mirrored it too:
> WebApp: http://repo.dustplanet.de/artifactory/webapp/#/artifacts/browse/tree/General/ext-release-local/net/gravitydevelopment/updater/updater/2.3/updater-2.3.jar
> 
> Direct access:
> http://repo.dustplanet.de/artifactory/ext-release-local

**Comment by gravitylow** [comment]
Hey, sorry folks.
The repo is back up now. I moved it to another hosting provider so fingers crossed it remains that way from now on.
