### ISSUE TITLE
Private plugins

### ISSUE THREAD

**Issue by linuxcodefire** [gravitylow/Updater#28]
I dont want to upload it to bukkit to use this.

**Comment by ibhh** [comment]
Then you have to use your own. This updater is required for official plugins because it's only allowed to download new files from bukkit servers.

**Comment by gravitylow** [comment]
This system is designed to work with the CurseForge API system, if you don't want to use that and aren't uploading to BukkitDev you are of course free to modify the file in accordance with the [MIT license](https://github.com/gravitylow/Updater/blob/master/LICENSE).
