### ISSUE TITLE
Maven Repo down

### ISSUE THREAD

**Issue by higgs01** [gravitylow/Updater#31]
Hello

Your maven repo on http://repo.gravitydevelopment.net/ seems to be down right now. If this is wanted, close the issue, otherwise a fix would be great since all builds are failing now

**Comment by gravitylow** [comment]
Hey, thanks for the ticket.

It should be back up now, can you verify for me?

**Comment by higgs01** [comment]
@gravitylow Works fine again.
Thank you for this fast fix
